name: Deploy to Render

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy to Render
        run: |
          echo "Deploying application to Render..."
          curl $RENDER_PRODUCTION_DEPLOYHOOK
