name: Deploy To Render

on:
  push:
    branches: [main]
  pull_request:
    branches:
      - main    

jobs:
  ci:
    name: Deploy To Render
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Tests
        run: |
          npm install
          npm run test

      - name: Deploy
      # Only run this step if the branch is main
        if: github.ref == 'refs/heads/main'
        env:
          RENDER_PRODUCTION_DEPLOYHOOK: ${{ secrets.RENDER_PRODUCTION_DEPLOYHOOK }}

        run: |
          echo "Deploying application to Render..."
          curl -f "$RENDER_PRODUCTION_DEPLOYHOOK" || echo "Deployment failed. Please check the webhook."