name: Deploy To Render

on:
  push:
    branches: [main]

jobs:
  render-deploy:
    strategy:
        matrix:
            node-version: [18.x, 20.x, 22.x]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4 
        with:
            node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: npm install
    
      - name: Build Application
        run: npm run build
      
    #   - name: Run Test
    #     run: npm run test

      - name: Deploy to Render
      # Only run this step if the branch is main
        if: github.ref == 'refs/heads/main' && env.RENDER_PRODUCTION_DEPLOYHOOK != ''
        env:
          RENDER_PRODUCTION_DEPLOYHOOK: ${{ secrets.RENDER_PRODUCTION_DEPLOYHOOK }}
        run: |
          echo "Deploying application to Render..."
          curl -f "$RENDER_PRODUCTION_DEPLOYHOOK" || echo "Deployment failed. Please check the webhook."