name: Cypress Component Test

on:
  pull_request:
    branches:
      - develop

jobs:
  cypress-tests:
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Using Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: npm install

      - name: Start Server
        run: npm run start
        working-directory: server

      - name: Wait for Server
        run: npx wait-on http://localhost:3001


      - name: Run Cypress Component Tests
        run: npm run test
